# Generated by Django 3.2.9 on 2021-11-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contraseña', models.CharField(blank=True, max_length=50, null=True, verbose_name='contraseña')),
            ],
        ),
    ]
